// CodeFusion Portfolio - Data and Content
// This file contains all dynamic data for services, projects, technologies, testimonials, and team members

import {
  Wifi,
  Cpu,
  Smartphone,
  Globe,
  Brain,
  Database,
  Cloud,
  Shield,
  Zap,
  Users,
  Code,
  Lightbulb,
  TrendingUp,
  Star,
  Award,
  Clock,
  MapPin,
  Mail,
  Phone,
  Github,
  Linkedin,
  Twitter,
} from "lucide-react";

// Services Data
export const SERVICES_DATA = [
  {
    id: "iot-development",
    title: "IoT Development",
    subtitle: "Connected Device Solutions",
    description: "End-to-end IoT development from sensor integration to cloud analytics, enabling smart connected systems.",
    icon: Wifi,
    category: "iot",
    features: [
      "Sensor Integration & Data Collection",
      "Real-time Data Processing",
      "Cloud Platform Development",
      "Mobile App Integration",
      "Security & Privacy Compliance",
      "Scalable Architecture Design",
    ],
    technologies: ["MQTT", "CoAP", "Node.js", "Python", "AWS IoT", "Azure IoT"],
    pricing: {
      starter: "$15,000",
      professional: "$35,000",
      enterprise: "Custom",
    },
    deliveryTime: "8-16 weeks",
    teamSize: "4-8 developers",
  },
  {
    id: "embedded-systems",
    title: "Embedded Systems",
    subtitle: "Custom Hardware Solutions",
    description: "Specialized embedded systems development with real-time performance and industrial reliability.",
    icon: Cpu,
    category: "embedded",
    features: [
      "Custom PCB Design",
      "Real-time Firmware Development",
      "RTOS Integration",
      "Hardware Testing & Validation",
      "Industrial Compliance",
      "Performance Optimization",
    ],
    technologies: ["C/C++", "FreeRTOS", "ARM Cortex", "FPGA", "CAN Bus", "Modbus"],
    pricing: {
      starter: "$25,000",
      professional: "$50,000",
      enterprise: "Custom",
    },
    deliveryTime: "12-24 weeks",
    teamSize: "3-6 engineers",
  },
  {
    id: "mobile-applications",
    title: "Mobile Applications",
    subtitle: "Cross-Platform Solutions",
    description: "Native and cross-platform mobile applications with seamless user experience and robust backend integration.",
    icon: Smartphone,
    category: "mobile",
    features: [
      "Native iOS & Android Development",
      "Cross-platform Solutions",
      "Offline Functionality",
      "Push Notifications",
      "Analytics Integration",
      "App Store Optimization",
    ],
    technologies: ["React Native", "Flutter", "Swift", "Kotlin", "Firebase", "AWS"],
    pricing: {
      starter: "$20,000",
      professional: "$45,000",
      enterprise: "Custom",
    },
    deliveryTime: "10-20 weeks",
    teamSize: "3-7 developers",
  },
  {
    id: "web-development",
    title: "Web Development",
    subtitle: "Modern Web Solutions",
    description: "Scalable web applications with modern technologies, responsive design, and optimal performance.",
    icon: Globe,
    category: "web",
    features: [
      "Responsive Web Design",
      "Progressive Web Apps",
      "E-commerce Solutions",
      "Content Management Systems",
      "API Development",
      "Performance Optimization",
    ],
    technologies: ["React", "Next.js", "Node.js", "TypeScript", "PostgreSQL", "AWS"],
    pricing: {
      starter: "$12,000",
      professional: "$30,000",
      enterprise: "Custom",
    },
    deliveryTime: "6-15 weeks",
    teamSize: "2-6 developers",
  },
  {
    id: "machine-learning",
    title: "Machine Learning",
    subtitle: "AI-Powered Solutions",
    description: "Custom machine learning models and AI solutions that drive business intelligence and automation.",
    icon: Brain,
    category: "ml",
    features: [
      "Custom ML Model Development",
      "Data Preprocessing & Analysis",
      "Model Training & Validation",
      "API Integration",
      "Model Monitoring",
      "Continuous Learning",
    ],
    technologies: ["Python", "TensorFlow", "PyTorch", "Scikit-learn", "FastAPI", "Docker"],
    pricing: {
      starter: "$30,000",
      professional: "$60,000",
      enterprise: "Custom",
    },
    deliveryTime: "12-20 weeks",
    teamSize: "4-8 data scientists",
  },
  {
    id: "technology-consulting",
    title: "Technology Consulting",
    subtitle: "Strategic Technology Guidance",
    description: "Expert technology consulting to help businesses make informed decisions and optimize their technology stack.",
    icon: Lightbulb,
    category: "consulting",
    features: [
      "Technology Assessment",
      "Architecture Review",
      "Technology Stack Selection",
      "Development Process Optimization",
      "Team Training",
      "Performance Audits",
    ],
    technologies: ["Architecture Design", "Process Optimization", "Best Practices", "Performance Analysis"],
    pricing: {
      starter: "$5,000",
      professional: "$15,000",
      enterprise: "Custom",
    },
    deliveryTime: "2-8 weeks",
    teamSize: "1-3 consultants",
  },
];

// Portfolio Projects Data
export const PORTFOLIO_DATA = [
  {
    id: "smart-home-iot",
    title: "Smart Home IoT Platform",
    subtitle: "Connected Home Automation System",
    description: "A comprehensive IoT platform for smart home automation with real-time monitoring and control.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
    category: "iot",
    technologies: ["React Native", "Node.js", "MongoDB", "MQTT", "TensorFlow", "AWS IoT"],
    client: "TechHome Solutions",
    duration: "6 months",
    teamSize: 8,
    status: "completed",
    liveUrl: "https://smarthome.demo.com",
    githubUrl: "https://github.com/codefusion/smart-home-iot",
    featured: true,
    tags: ["IoT", "Smart Home", "Automation", "Real-time", "Mobile App"],
  },
  {
    id: "industrial-automation",
    title: "Industrial Automation Controller",
    subtitle: "Embedded System for Manufacturing",
    description: "Custom embedded controller for industrial automation with real-time processing capabilities.",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop",
    category: "embedded",
    technologies: ["C/C++", "FreeRTOS", "ARM Cortex-M7", "CAN Bus", "Modbus"],
    client: "ManufactureTech Industries",
    duration: "8 months",
    teamSize: 6,
    status: "completed",
    githubUrl: "https://github.com/codefusion/industrial-controller",
    featured: true,
    tags: ["Embedded", "Industrial", "Real-time", "Safety", "Automation"],
  },
  {
    id: "fitness-tracker-app",
    title: "Advanced Fitness Tracker",
    subtitle: "Mobile App with Health Analytics",
    description: "Cross-platform mobile application for fitness tracking with advanced health metrics and social features.",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop",
    category: "mobile",
    technologies: ["React Native", "TypeScript", "Redux", "Node.js", "PostgreSQL"],
    client: "FitLife Technologies",
    duration: "5 months",
    teamSize: 7,
    status: "completed",
    liveUrl: "https://fittracker.app",
    githubUrl: "https://github.com/codefusion/fitness-tracker",
    featured: false,
    tags: ["Mobile", "Fitness", "Health", "Cross-platform", "Social"],
  },
  {
    id: "ecommerce-platform",
    title: "Modern E-commerce Platform",
    subtitle: "Full-Stack Web Application",
    description: "Scalable e-commerce platform with advanced features, payment integration, and admin dashboard.",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop",
    category: "web",
    technologies: ["React", "Next.js", "TypeScript", "Node.js", "PostgreSQL", "Stripe"],
    client: "ShopSmart Retail",
    duration: "4 months",
    teamSize: 5,
    status: "completed",
    liveUrl: "https://shopdemo.codefusion.com",
    githubUrl: "https://github.com/codefusion/ecommerce-platform",
    featured: false,
    tags: ["E-commerce", "Web App", "Payment", "Mobile", "SEO"],
  },
  {
    id: "predictive-analytics",
    title: "Predictive Analytics Engine",
    subtitle: "Machine Learning for Business Intelligence",
    description: "AI-powered analytics platform that predicts business trends and provides actionable insights.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
    category: "ml",
    technologies: ["Python", "TensorFlow", "PyTorch", "Scikit-learn", "FastAPI"],
    client: "DataInsight Corp",
    duration: "7 months",
    teamSize: 9,
    status: "completed",
    githubUrl: "https://github.com/codefusion/predictive-analytics",
    featured: true,
    tags: ["Machine Learning", "Analytics", "Predictions", "AI", "Business Intelligence"],
  },
];

// Technology Stack Data
export const TECH_STACK_DATA = [
  {
    id: "react",
    name: "React",
    category: "frontend",
    description: "Modern JavaScript library for building user interfaces",
    icon: "⚛️",
    proficiency: "expert",
    yearsOfExperience: 6,
    projectsUsed: 50,
    bgColor: "bg-blue-100 dark:bg-blue-900/20",
    textColor: "text-blue-800 dark:text-blue-200",
  },
  {
    id: "nextjs",
    name: "Next.js",
    category: "frontend",
    description: "React framework for production with SSR and static generation",
    icon: "▲",
    proficiency: "expert",
    yearsOfExperience: 4,
    projectsUsed: 25,
    bgColor: "bg-gray-100 dark:bg-gray-900/20",
    textColor: "text-gray-800 dark:text-gray-200",
  },
  {
    id: "nodejs",
    name: "Node.js",
    category: "backend",
    description: "JavaScript runtime for server-side development",
    icon: "🟢",
    proficiency: "expert",
    yearsOfExperience: 6,
    projectsUsed: 45,
    bgColor: "bg-green-100 dark:bg-green-900/20",
    textColor: "text-green-800 dark:text-green-200",
  },
  {
    id: "python",
    name: "Python",
    category: "backend",
    description: "High-level programming language for data science and web development",
    icon: "🐍",
    proficiency: "expert",
    yearsOfExperience: 7,
    projectsUsed: 35,
    bgColor: "bg-yellow-100 dark:bg-yellow-900/20",
    textColor: "text-yellow-800 dark:text-yellow-200",
  },
  {
    id: "react-native",
    name: "React Native",
    category: "mobile",
    description: "Cross-platform mobile development with React",
    icon: "📱",
    proficiency: "expert",
    yearsOfExperience: 4,
    projectsUsed: 20,
    bgColor: "bg-blue-100 dark:bg-blue-900/20",
    textColor: "text-blue-800 dark:text-blue-200",
  },
  {
    id: "tensorflow",
    name: "TensorFlow",
    category: "ml",
    description: "Open-source machine learning framework",
    icon: "🧠",
    proficiency: "expert",
    yearsOfExperience: 4,
    projectsUsed: 20,
    bgColor: "bg-orange-100 dark:bg-orange-900/20",
    textColor: "text-orange-800 dark:text-orange-200",
  },
];

// Testimonials Data
export const TESTIMONIALS_DATA = [
  {
    id: "techhome-solutions",
    name: "Sarah Johnson",
    role: "CTO",
    company: "TechHome Solutions",
    companyLogo: "🏠",
    rating: 5,
    content: "CodeFusion transformed our IoT platform from concept to reality in just 6 months. Their expertise in embedded systems and real-time data processing exceeded our expectations.",
    projectType: "IoT Platform Development",
    projectDuration: "6 months",
    isFeatured: true,
    tags: ["IoT", "Embedded Systems", "Real-time Processing"],
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
  },
  {
    id: "manufacturetech",
    name: "Michael Chen",
    role: "Engineering Director",
    company: "ManufactureTech Industries",
    companyLogo: "🏭",
    rating: 5,
    content: "Working with CodeFusion on our industrial automation controller was a game-changer. Their deep understanding of ARM architecture resulted in a 30% performance improvement.",
    projectType: "Industrial Automation System",
    projectDuration: "8 months",
    isFeatured: true,
    tags: ["Embedded Systems", "ARM", "Real-time OS"],
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
  },
  {
    id: "fitlife-tech",
    name: "Emily Rodriguez",
    role: "Product Manager",
    company: "FitLife Technologies",
    companyLogo: "💪",
    rating: 5,
    content: "CodeFusion delivered an exceptional fitness tracking app that exceeded our user engagement goals. We achieved a 4.8/5 rating with 100,000+ active users.",
    projectType: "Mobile Application",
    projectDuration: "5 months",
    isFeatured: false,
    tags: ["React Native", "Cross-platform", "Real-time Sync"],
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
  },
];

// Team Members Data
export const TEAM_DATA = [
  {
    id: "alex-chen",
    name: "Alex Chen",
    role: "Co-Founder & CEO",
    title: "Chief Executive Officer",
    bio: "Visionary leader with 15+ years of experience in technology innovation and business strategy.",
    expertise: ["IoT Architecture", "Business Strategy", "Product Vision", "Team Leadership"],
    experience: "15+ years in tech leadership",
    education: "MS Computer Science, Stanford University",
    location: "San Francisco, CA",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=face",
    isFounder: true,
    isFeatured: true,
    socialLinks: {
      github: "https://github.com/alexchen",
      linkedin: "https://linkedin.com/in/alexchen",
      twitter: "https://twitter.com/alexchen",
      email: "alex@codefusion.com",
    },
    skills: [
      { name: "IoT Development", level: "expert", icon: Wifi },
      { name: "Business Strategy", level: "expert", icon: TrendingUp },
      { name: "Team Leadership", level: "expert", icon: Users },
    ],
    funFact: "Built his first IoT device at age 12 using Arduino",
    favoriteTech: "Raspberry Pi & MQTT",
    joinedDate: "January 2020",
  },
  {
    id: "sarah-rodriguez",
    name: "Sarah Rodriguez",
    role: "Co-Founder & CTO",
    title: "Chief Technology Officer",
    bio: "Technical architect and engineering leader with expertise in scalable systems and machine learning.",
    expertise: ["System Architecture", "Machine Learning", "Cloud Infrastructure", "Technical Leadership"],
    experience: "12+ years in software engineering",
    education: "PhD Computer Science, MIT",
    location: "Boston, MA",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=300&h=300&fit=crop&crop=face",
    isFounder: true,
    isFeatured: true,
    socialLinks: {
      github: "https://github.com/sarahrodriguez",
      linkedin: "https://linkedin.com/in/sarahrodriguez",
      twitter: "https://twitter.com/sarahrodriguez",
      email: "sarah@codefusion.com",
    },
    skills: [
      { name: "Machine Learning", level: "expert", icon: Brain },
      { name: "System Architecture", level: "expert", icon: Shield },
      { name: "Cloud Infrastructure", level: "expert", icon: Cloud },
    ],
    funFact: "Can solve Rubik's cube in under 2 minutes",
    favoriteTech: "TensorFlow & Kubernetes",
    joinedDate: "January 2020",
  },
];

// Export all data
export default {
  SERVICES_DATA,
  PORTFOLIO_DATA,
  TECH_STACK_DATA,
  TESTIMONIALS_DATA,
  TEAM_DATA,
};
